### ISSUE TITLE
Proper Gradle build-cache interaction w/ the Gradle Plugin

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#1022]
Currently the gradle plugin runs at every gradle invocation even if the underlying code hasn't changed. The gradle plugin should be sensitive to its inputs and only run tests/start nessie service if its inputs have changed.

**Comment by snazy** [comment]
TL;DR:

* The `quarkus.test.http-port` system property must not be in the Gradle `Test` tasks system property, because it's a rather random port, and system properties are part of the Gradle build-cache-key. This has been moved to a `CommandLineArgumentProvider` that's added to `Test.getJvmArgumentProviders()`.
* Gradle has no explicit support to "run a task only if another task would run". I.e. the `quarkus-start` task would always run, even if the `test` task is cached. The workaround here is to let the Nessie-Quarkus-App start via a `Test.doFirst()`-closure.

See #1042
