### ISSUE TITLE
investigate relaxing the pinned deps on python libs

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#1137]
It is fairly hard to install pynessie in some envs because the version pins are so strong. End up hacking to get it installed.

**Comment by snazy** [comment]
I know it was an issue on Google Colab until last week. However, today a `pip install pynessie ...` just passes. There are warnings, but those don't prevent the installation.
But some things do not work as expected on Google Colab. For example, a `spark.sql("select * from foo.bar`").toPandas()` fails on Google Colab, because some `get_result` is missing in `NotebookFormatter`, so probably a compatibility issue w/ the preinstalled deps in Colab.
