### ISSUE TITLE
Handle relative hashes in Reference

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#1352]
Currently a reference is either:

* a named tag or branch
* a hash (eg hex number)

We don't support things like `HEAD~1` or other ways to get relative hashes. We should add support for this. Probably only on the client side

**Comment by snazy** [comment]
Added to the 1.0.0 milestone. Not sure, but maybe we need some API changes to support relative hashes and/or relative/absolute dates/times

**Comment by snazy** [comment]
This one (index-relative hashes + something line ` named-ref # timestamp `) very likely requires a server roundtrip using something like `Reference HttpTreeApi.findCommit ( @NotNull String refName, @Nullable String relativeHashNotion, @Nullable forTimestamp, boolean returnHashBeforeOrAfterTimestamp )` (<-- NOT a proposal!).

Not a very big deal to implement that, but figuring out the right "string representation" across all tools (Iceberg, Delta, etc) that covers exact hashes, relative hashes, timestamps in all combinations takes time and should be "done right" (since it's for or after GA).

**Comment by tomekl007** [comment]
Couple questions (@snazy):
- do we want to support the ~X (i.e.: `master~10`) syntax and ^ (i.e.: `master^`) syntax or only the former? 
- regarding the signature that you gave:
`Reference HttpTreeApi.findCommit ( @NotNull String refName, @Nullable String relativeHashNotion, @Nullable forTimestamp, boolean returnHashBeforeOrAfterTimestamp )` I am not sure why there is `forTimestamp` and `returnHashBeforeOrAfterTimestamp`. Do we want to support also timestamps as a part of this ticket, or only relative hashes? I don't see how timestamp and relative hashes are related - maybe we should handle those separately?
-  re: `forTimestamp`: should this be of a Instant type)
- If we want to be able to pass some complex syntax, maybe we could yield towards more generic mechanism that allows caller to be more flexible? For example, we are using CEL for such a purpose - not sure if this is a good use case here but maybe we could leverage it as well. The other solution is antlr (https://www.antlr.org/) but it is quite heavy and complex - not sure if we need it here.

**Comment by snazy** [comment]
I'd say, let's stick with CEL and do it on the client side for now - maybe in some separate class that can later be ported to the server side, when it becomes necessary.

**Comment by tomekl007** [comment]
What about the rest of the questions? What do we want to support?

**Comment by tomekl007** [comment]
>stick with CEL and do it on the client side for now
@snazy can you elaborate more on that? Do you mean we can handle that also via `filter` or should we create a new attribute (something like `relativeHashSelector`)?
