### ISSUE TITLE
Handle times in SQL extensions better

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#1452]
We do not handle timezones well in the `AT` date for using a reference.

Actually, we need a story around what we/users mean when we say for example "AFTER 2021-04-01". It means different thing to different people especially across time zones. E.g. if someone from the UK runs this query against data generated in Sydney, all the data  generated between 00:00 Sydney local time and 00:00 UTC would be missed.

_Originally posted by @snazy in https://github.com/projectnessie/nessie/pull/1373#discussion_r653479616_

**Comment by snazy** [comment]
Related: #1352

**Comment by snazy** [comment]
See #1352, probably worth to postpone this and 1352 to after 1.0.0

**Comment by rymurr** [comment]
Want to discuss this so adding back to milestone

**Comment by tomekl007** [comment]
A couple of questions and observations:
I see that the relevant code is in the `NessieUtils`:
```   
val timestamp = tsOrHash
      .map(x => x.replaceAll("`", ""))
      .map(x => {
        try {
          ZonedDateTime.parse(x).toInstant
            LocalDateTime.parse(x).atZone(ZoneOffset.UTC).toInstant
        } catch {
          case e: DateTimeParseException =>
            throw new NessieNotFoundException(
              "Invalid timestamp provided: " + e.getMessage
            )
        }
      })
      .orNull
```
I am not able to find any other place where the conversion may happen.
Looking at this PR:
https://github.com/apache/iceberg/pull/1825/files
it seems that the underlying API is based on timestamp, not date-time. So we want to transform the zonedDateTime to timestamp. 
Currently, we were allowing our clients (via spark SQL) to provide only non-zoned date time because of the conversion here:
`LocalDateTime.parse(x).atZone(ZoneOffset.UTC).toInstant` - if the zone (`String time = DateTimeFormatter.ISO_DATE_TIME.format(ZonedDateTime.now());`) is provided, the processing fails and the underlying problem is propagated to the caller as smth like:
```
Invalid timestamp provided: Text '2022-06-28T13:29:01.288763+02:00[Europe/Warsaw]' could not be parsed, unparsed text found at index 26
```
**So my question is whether we want to allow our clients to pass both: Zoned and nonZoned dates to the SQL API?**
From the backward compatibility perspective, it seems that we need to keep the non-zoned version as well.

**Comment by snazy** [comment]
Leaving the concrete implementation (`NessieUtils`) aside, I think that the user-facing Spark-SQL syntax should be as close as possible to what Spark does - basically using what Spark provides. Maybe there's a way to take whatever Spark provides - like "let Spark parse the timestamp" and use the parsed `Timestamp`.

Re: time zones - that would be good, yes. The original issue here was that there is no support for time zones at all.

But we should implement something that is different from what Spark-SQL does (from a user's POV).

**Comment by tomekl007** [comment]
I think we have two solutions that we can choose:
1. Leveraging Spark functions
We can leverage `to_utc_timestamp` and `utc_timestamp`:
```
spark.sql("""select to_utc_timestamp('2012-11-20T17:39:37Z', "America/New_York")""").show()
```
Gives the timestamp in the UTC format:
```
2012-11-20 23:39:37|
```
However, it requires an end-user to handle the conversion. Also, the end-user needs to pass the zone name in a "spark format". The format of the date passed to the function also needs to be specific; for example, we cannot pass milliseconds because the spark will trim those with seconds:
```
 spark.sql("""select to_utc_timestamp('2022-06-29T09:26:07.97Z', "America/New_York")""").show()
+-----------------------------------------------------------+
|to_utc_timestamp(2022-06-29T09:26:07.97Z, America/New_York)|
+-----------------------------------------------------------+
|                                       2022-06-29 15:26:...|
+-----------------------------------------------------------+
```
For the `utc_timestamp` function, the end-user needs to set the `timeZone` on the spark session conf:
```
spark.conf.set("spark.sql.session.timeZone", "America/New_York")
```
and then pass the date-time to the function:
```
spark.sql("""select to_timestamp('2012-11-20T17:39:37Z', "yyyy-MM-dd'T'HH:mm:ssz")""").show()
```
Atop of that, our current API is using `String` to represent the date-time type. The conversion functions are returning a timestamp so the user needs to cast those to `String`. If we don't want to break the compatibility of our current SQL API, we need to  tick to the `String` type

Taking all the factors into account, this solutions does not seems to be UX friendly.
 

2. Pass the date with timezone and use the custom parsing in the `NessieUtils`
Allow users to pass the date time with zone: `DateTimeFormatter.ISO_DATE_TIME.format(ZonedDateTime.now())` via `ISO_DATE_TIME`  but also without timezone `DateTimeFormatter.ISO_LOCAL_DATE_TIME.format(LocalDateTime.now(ZoneOffset.UTC))` and assume it's a UTC. Handle both in the `NessieUtils`

thoughts? I think that the 2nd options is better from the end-user perspective.

**Comment by snazy** [comment]
I don't recall why we relied on UTC and "primitive long" values. Probably no particular good reason though.

Maybe we could:
* respect `SQLConf`'s `sessionLocalTimeZone` + [`spark.sql.session.timeZone`](https://jaceklaskowski.gitbooks.io/mastering-spark-sql/content/spark-sql-properties.html#spark.sql.session.timeZone) (in SQL: `SET TIME ZONE`)
* Leverage Sparks `TimestampType` when we return timestamps (e.g. in the commit log via `BaseShowLogExec`)
* Either leverage Spark's default format, if such a thing exists, via Spark`s [`to_timestamp`](https://spark.apache.org/docs/2.3.0/api/sql/index.html#to_timestamp) (if that's possible) or use the ISO_DATE_TIME that you proposed in (2)

**Comment by tomekl007** [comment]
> respect SQLConf's sessionLocalTimeZone + [spark.sql.session.timeZone](https://jaceklaskowski.gitbooks.io/mastering-spark-sql/content/spark-sql-properties.html#spark.sql.session.timeZone) (in SQL: SET TIME ZONE) - 

this is what exactly what I was describing in the:

> For the utc_timestamp function, the end-user needs to set the timeZone on the spark session conf:

> Leverage Sparks TimestampType when we return timestamps (e.g. in the commit log via BaseShowLogExec)

I am not sure what you mean by that. How does it solve our problem? We can convert String -> Timestamp or another way around. But still we need to decide how to pass the time-zone and whether we can change the SQL API to accept timestamp and not String

**Comment by tomekl007** [comment]
**Decision:**
We start accepting dateTime with time zone only. If the user passes the dateTime without zone:
`"2022-06-29T09:26:07.974992"` we should throw an exception denoting that the user needs to pass the zone explicitly. The new dataTime format should be: `2022-06-29T11:26:07.976777+02:00`. It means that we are breaking the compatibility of the current API, but we concluded that having an exception with a meaningful message would be enough in that case. Also, Nessie is not `1.x` version yet, so the API changes can be justified.
