### ISSUE TITLE
[CLI] Pynessie 0.12.0 throws `ModuleNotFoundError: No module named 'pynessie.auth'`

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#2528]
![image](https://user-images.githubusercontent.com/5889404/139203719-369ae12a-ca10-4b0d-b79d-93241a9e542f.png)

I see that in the `nessie_client.py `this import statement is newly added  `.auth.config import setup_auth`
I should do anything else to make it work ?

cc: @dimas-b

**Comment by dimas-b** [comment]
I wonder why `pytest` did not catch this earlier :thinking: @omarsmak : any insight?

**Comment by omarsmak** [comment]
> I wonder why `pytest` did not catch this earlier 🤔 @omarsmak : any insight?

The issue is that here, when we do something like `python setup.py install` which will install the module into the `site-packages` folder of your python env, it was skipping the `auth` module since didn't contain `__init__`. Why `pytest` didn't catch it? Well, I 'think' because it didn't need to install it perhaps, it was the using module as it is from `pynessie` folder 🤔
