### ISSUE TITLE
Prevent accidental deletion of the default branch

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#3401]
In production environments it must not be possible to delete the default branch.

This is probably an easy fix in terms of code, but might involve touching a bunch of tests.
For the tests, it should be fine to re-assign the default branch to "beginning of time" instead of deleting + re-creating it.

**Comment by snazy** [comment]
@XN137 or @tomekl007  if you don't have anything urgent on your plate, mind looking into this one?

**Comment by XN137** [comment]
i am working on updating the demos atm but i can also look into this, unless @tomekl007  is already looking for a task to work on?

**Comment by XN137** [comment]
https://github.com/projectnessie/nessie/pull/3415 added a new access check `DELETE_DEFAULT_BRANCH` however we do not yet prevent default branch deletion out of the box, thus re-opening this ticket.

i lack context on how ideally we could achieve this now, any ideas @snazy  ?

**Comment by snazy** [comment]
IMO it's good-enough :tm: to have a check for this. There's not much more we can actually do here. At best, we can add a default rule to application.properties to prevent that. But let's leave this ticket open for now, maybe we come to another conclusion.

**Comment by tomekl007** [comment]
Not sure what's the current status of it. What was the purpose of: https://github.com/projectnessie/nessie/pull/3415/files
if we still allow removing the default branch? @XN137 @snazy can you elaborate more?

**Comment by XN137** [comment]
the PR adds a new configurable access check `DELETE_DEFAULT_BRANCH`, so that when the access checker is enabled, you can control what users can delete the default branch.
the first commit in the PR suggested to universally prevent deletions of the default branch, but as mentioned in the PR description after more discussions i was following the recommendation of @snazy to model this via the access check instead.
but tbh i dont remember the details on why this was better, when it doesnt allow us to prevent accidental deletion out of the box easily.

the current status is explained in the comments above: it is unclear how we should prevent the default branch from being deleted out of the box (with or without the access checker enabled).

the question might be: what legitimate use cases are there for deleting the default branch? (resetting a repo?)

if there are legitimate reasons, then admin users should be able to do it.
with access checker we provide the ability to control this, but end users would need to configure who is allowed and who isnt (we could maybe add a default rule that doesnt let anyone do it).
without access checker we dont know what users are admins, so everyone can do it atm (maybe it should be: nobody can do it... but maybe then nobody can reset a repo and start from scratch idk).

**Comment by snazy** [comment]
We should probably switch to the behavior that nobody can delete the default branch. It likely causes a lot of problems when the default branch is deleted. If the default branch does not exist, a lot of operations are likely to fail. There's likely no reason to allow deletion of the default branch, even w/o authorization.

**Comment by XN137** [comment]
ok maybe then we should revert https://github.com/projectnessie/nessie/pull/3415 and only cherry pick its first commit again

**Comment by tomekl007** [comment]
> ok maybe then we should revert #3415 and only cherry pick its first commit again

good point, I see you did that already, I will do that and submit a PR
