### ISSUE TITLE
Ensure rest apis handle branches & tags with slashes in them

### ISSUE THREAD

**Issue by jacques-n** [projectnessie/nessie#395]

**Comment by laurentgo** [comment]
I guess it depends on what handle means. Current REST API either accept named referenced as a path component. If the path component is encoded properly, then the REST API should work correctly. But if the expectation is that slashes do not need to be encoded, this is something we  might need to address. 

That said, it looks like OpenAPI spec does not support path parameters with slashes according to https://github.com/OAI/OpenAPI-Specification/issues/892

**Comment by laurentgo** [comment]
I was curious how Github was handling this as they recently published OpenAPI specs for their API, and it looks like they are using some kind of extension: https://github.com/github/rest-api-description/blob/main/extensions.md

Their doc states that both actually works, so a OpenAPI client could actually use the encoded form while a human user would not have to deal with encoding...

**Comment by snazy** [comment]
Not sure whether supporting unencoded reference names as parameters would be a good thing to have, because even if we can get it properly working on the server side, it still leaves the risk of having ambiguous requests. E.g. consider a reference name that ends in `/entries` or `/log` or so.

The issue here is that our client doesn't properly uri-encode the reference names (`javax.ws.rs.client.WebTarget#path` blindly appends the given string). That's actually easy to fix.

**Comment by laurentgo** [comment]
Yes, I'm aware of the ambiguity issue, which is why I commented on it early, hoping that @jacques-n could clarify :)

There's a bug in our REST client for sure, but not sure if this is what Jacques had in mind when he opened that ticket.
