### ISSUE TITLE
`gc-base` module must not depend on Iceberg

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#4626]
`gc-base` is intended to contain the common Nessie-GC code for any table-format. Iceberg gets its implementation in a separate module.

References to Iceberg code must therefore not be present in the `gc-base` module.

**Comment by ajantha-bhat** [comment]
Currently, `gc-base` module needs to write its output to the spark table. 
It can be any table format but it has to use existing nessie catalog. (Don't want to force user to configure another non-Nessie catalog while working on Nessie gc)

And with the Nessie catalog, only Iceberg tables are better handled. So, chose Iceberg format.

I can move this `IdentifiedResultsRepo` code to `gc-iceberg` module. But `gc-base` module becomes incomplete or will have a dependency on `gc-iceberg` module. 

I will check about having a default implementation as spark table with spark default catalog and open a `gcParams` to provide className of the repo impl.

**Comment by ajantha-bhat** [comment]
I tired removing iceberg dependency on gc-base module here
https://github.com/projectnessie/nessie/commit/f08ae70309e30f53cbcc645483c69d57b3015744

Instead of the Iceberg table, I am trying to store it as a normal parquet table. But I am facing issues as to which catalog to use?
  I used `session.sessionState().catalogManager().currentCatalog();`
  It gives me many errors while creating a table. ()
  I have only Nessie catalog configured in spark conf and really don't want to force user to have another catalog while working on Nessie GC.
  
  I will work on this once other things are handled for gc.

**Comment by snazy** [comment]
Implemented via #4991
