### ISSUE TITLE
Error: "Failed to export spans" when running with default config

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#5655]
* Run local Nessie (e.g. Quarkus dev mode). 
* Make some requests
* Quarkus logs this error:

```
2022-12-07 19:41:06,633 SEVERE [io.ope.exp.int.grp.OkHttpGrpcExporter] (OkHttp http://localhost:4317/...) Failed to export spans. 
The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317
```

**Comment by snazy** [comment]
Haven't seen this one anymore, closing

**Comment by adutra** [comment]
Just for future reference: this error message is still visible and is related to the [`quarkus.opentelemetry.tracer.exporter.otlp.endpoint`](https://quarkus.io/guides/opentelemetry#quarkus-opentelemetry_quarkus.opentelemetry.tracer.exporter.otlp.endpoint) setting.

This setting is mandatory for OpenTelemetry to work properly and should always be explicitly set in production mode.

In development mode (quarkus:dev), however, thanks to the specific behavior in [`OtlpRecorder`](https://github.com/quarkusio/quarkus/blob/2.16.3.Final/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/OtlpRecorder.java#L20-L23), this setting is automatically set to `http://localhost:4317` if not present.

Because of that, the `LateBoundBatchSpanProcessor` bean gets configured, and tries to contact the OTLP collector at http://localhost:4317 but fails since no collector was deployed – hence the error message.

In #6153 I added a few troubleshooting notes about this to site/docs/try/configuration.md, see https://github.com/projectnessie/nessie/commit/1e491aa1b32f36d8ce2e564c24209f028e29ddad.
