### ISSUE TITLE
Evaluate how reference-names with slashes can be properly handled in human-facing URLs

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#584]
Reference names (branches, tags) can contain slashes. The REST API requires those reference names to be properly escaped, which is fine, because it's intended for machine-to-machine communication.

But users (humans) probably want "nice to read" URLs like `https://my-nessie-server-ui/tree/my/project/branch/name/commits` in the UI, which reads better than `https://my-nessie-server-ui/tree/my%2fproject%2fbranch%2fname/commits`

**Comment by snazy** [comment]
From two experiments against GH:
First, create branch `tree/bom` -> then a create-branch `tree` fails. Other way aound:
First, create branch `tree` -> then a create-branch `tree/bom` fails.
So there seems to be some path-ish validation.

**Comment by dimas-b** [comment]
Another point: Even though using `%2F` in the URL path currently works, it is inconvenient for programmatic use because tools (e.g. `rest-assured`) will generally re-escape the `%` if it is passed to them in the URL path. At the same time tools will not escape `/` charts that are part of the ref name because they lack the knowledge of its special meaning.
