### ISSUE TITLE
nessie-gc: Support for position and equality delete files in Iceberg table

### ISSUE THREAD

**Issue by marvin-roesch** [projectnessie/nessie#7477]
**Description**: Currently, nessie-gc does not support the Iceberg table V2 feature of position and equality delete files. The mark period of the GC process works fine, but deleting the files leads to an exception from Iceberg with message `Cannot read a delete manifest with a ManifestReader`. It looks like nessie-gc is trying to treat delete manifests like data manifests.

I wasn't sure whether to file this as a bug report or feature suggestion, as it kind of sits somewhere in-between.

**Expected Use Cases**: Garbage collection for V2 Iceberg tables that make use of position and equality delete files.

**Comment by ajantha-bhat** [comment]
Thanks for reporting the issue. 

From the review, Indeed there is a problem in `IcebergContentToFiles#allDataFiles`. 
I hope the callstack is also from the same place. 

https://github.com/projectnessie/nessie/blob/79a85088f67e9c573bd7e3f2662ad94c582c8cb7/gc/gc-iceberg/src/main/java/org/projectnessie/gc/iceberg/IcebergContentToFiles.java#L156

The `ManifestFiles#readPaths()` is meant only for data files. We need to use `ManifestFiles#open()` which can handle both data and delete files. 

Adding the testcase is non-trivial. Will keep you updated once the fix is ready.

**Comment by marvin-roesch** [comment]
That is what I gathered as well, @ajantha-bhat. I was looking into providing the implementation for delete files myself, but the Iceberg APIs for manifests don't make it easy with lots of things being package-private. Glad to hear this issue is being worked on!
