### ISSUE TITLE
New `prev_ptr` column in refs table does not get created automatically

### ISSUE THREAD

**Issue by marvin-roesch** [projectnessie/nessie#7630]
**What happened**: We upgraded in-place to 0.72.0 and started getting errors of the following nature when running queries from Trino:
```
Failure on server, propagated to client. Status: 500 Internal Server Error, Message: java.lang.RuntimeException: Unhandled SQL exception, caused by org.postgresql.util.PSQLException: ERROR: column "prev_ptr" does not exist
```

**What you expected to happen**: The upgrade should have worked just fine without manual intervention as per the [server upgrade notes](https://projectnessie.org/try/server-upgrade/).

**How to reproduce it (as minimally and precisely as possible)**: Update a Nessie server backed by an existing database from version 0.71.1 to 0.72.0.

**Details**:
- Nessie server type (docker/built from source) and version: Docker v0.72.0 on Kubernetes
- Client type (Ex: UI/Spark/pynessie ...) and version: Trino 422

It appears the new column was not included in whatever ensures the correct state of the underlying (Postgres) database and so a manual update of the schema is required, but finding that info is difficult, too.

**Comment by snazy** [comment]
Sorry to head that the upgrade did not work as smoothly as expected.

There are checks in the JDBC + Cassandra backends that compare the current schema against the expected schema. The new column however is not included in that check in 0.72.0, so the server message indicating the DDL changes probably did not print the DDL.

Nessie does not automatically _change_ an existing schema, because we cannot expect to have the right permissions to perform DDL statements.

**Comment by marvin-roesch** [comment]
Ah, that is good to know. I was under the impression it would try to migrate the schema as well since it *does* try to create it (as far as I can tell from [`JdbcBackend`](https://github.com/projectnessie/nessie/blob/main/versioned/storage/jdbc/src/main/java/org/projectnessie/versioned/storage/jdbc/JdbcBackend.java)). Crashing at startup and seeing what exactly needs to be added is good as well, though! Certainly better than failing at query time.

**Comment by snazy** [comment]
Closing this one, because #7631 has been merged.
