### ISSUE TITLE
`ITOAuth2Client` consistently failing locally

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#7918]
### Issue description

`./gradlew intTest`

```
> Task :nessie-client:intTest

ITOAuth2Client > testOAuth2ClientInitialRefreshToken(GrantType) > [4] initialGrantType=DEVICE_CODE FAILED
    java.lang.RuntimeException at ITOAuth2Client.java:181
        Caused by: java.lang.NullPointerException at JavaHttpClient.java:68

ITOAuth2Client > testOAuth2ClientDeviceCodeAccessDenied() FAILED
    java.lang.AssertionError at ITOAuth2Client.java:321

```

**Comment by adutra** [comment]
Update: this is failing only for Java 21. I'm investigating.

**Comment by adutra** [comment]
Well I finally have an explanation:

Java 17 and 21 have different defaults for the `Accept` header:

* Java 17: `text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2`
* Java 21: `*/*`

This will have a surprising consequence when trying to POST the user code to `realms/master/device`: the REST resource in Keycloak that handles this user endpoint _also_ handles the `realms/master/auth/device` endpoint, which clients are supposed to contact in order to get a fresh user code:

```java
    @Path("")
    @POST
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    @Produces(MediaType.APPLICATION_JSON)
    public Response handleDeviceRequest() // realms/master/auth/device (called by clients)

    @Path("/")
    @POST
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    public Response verifyUserCode() // realms/master/device (called by users)
```

See https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/grants/device/endpoints/DeviceEndpoint.java

The 2 endpoints differ by 2 things:

1. The trailing slash: `@Path("")` vs `@Path("/")`;
2. The first endpoint declares to produce JSON, whereas the second doesn't declare what it produces.

Given that the `ResourceOwnerEmulator` class currently does NOT include the trailing slash, when the `Accept` header contains `text/html`,  then the `verifyUserCode` endpoint is selected, which is correct. When the `Accept` header contains only `*/*` however, the `handleDeviceRequest` endpoint is selected instead, which is wrong and results in a 401 response.

Having 2 endpoints differing only by the trailing slash is obviously not a good practice, but that's the way it is.

There are 2 ways of solving this:

* Include `text/html` in the `Accept` header;
* Include a trailing slash in the URL.

I am going with the 2nd option.

**Comment by adutra** [comment]
Well, nope: the `Accept` header _must_ contain `text/html` for the right endpoint to be selected.
