### ISSUE TITLE
REST API change: Move `message` parameter of ContentsApi.setContents to POST body

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#812]
A commit message can be very long, but since it is submitted in the URL, it is implicitly restricted by "practical limits" in the network infrastructure.

Although the HTTP RFCs do not put a limit on the length of a URL, actual HTTP implementations _can_ put a limit and reply with a HTTP/414, if the request URL is too long.

Applies to
* `ContentsApi.setContents`
* `ContentsApi.delete`
* `TreeApi.commitMultipleOperations`
* `TreeApi.transplantCommitsIntoBranch`

**Comment by rymurr** [comment]
I am not 100% sure what to do here. The practical limit for this seems to be upwards of 8k in most places. Old IE being the exception and limiting to 2048 chars. So this puts a realistic upper limit on the commit message however we prob would want to restrict its size anyways at some stage as 8k is a lot of space for a message.

By adding the data to the body we now have to expose a commit metadata like object in the public api rather than assembling it from query params and credentials. And the body then becomes a composite of the commit meta and the actual contents object. Making it harder to implement in other languages and cascading a bunch of changes into js and python.

As part of #779 I am proposing moving to headers for new commit meta related items and leaving the commit message as is. Headers have an 8k limit each in the oldest web servers and are less disruptive to the already published spec. Wondering what other peoples thoughts are?

**Comment by rymurr** [comment]
Having said that the commit meta object is already exposed via the log api so maybe it isn't so bad...

**Comment by snazy** [comment]
The question here is not only whether a specific browser or particular HTTP endpoint can handle 4k or 8k URIs or header-fields. The question is about whether individual HTTP libraries and network components (proxies, firewalls, etc) can handle that, which I frankly doubt.

Implicitly adding a limit by using a HTTP header for e.g. the commit-message makes Nessie dependent on limitations of network infrastructure and setup. Some network-infrastructure might just block unknown headers due to security policies that some people have in place.

Using headers also makes it impossible to use compression for e.g. the commit-message.

It would be very disappointing for Nessie users, if their application completely stops or fails in an unrecoverable way, because some automatically generated commit message is 1 byte too big.

**Comment by rymurr** [comment]
> It would be very disappointing for Nessie users, if their application completely stops or fails in an unrecoverable way, because some automatically generated commit message is 1 byte too big.

Totally agree. In some ways that is the world we live in. The entire application is designed around what a network might support. Otherwise we would be on HTTP/2 and grpc or so. What is a good trade-off though? To me the addition of commit-meta into the body confuses the API and it still doesn't solve the problem of the `DELETE` endpoint. Basically, where do we want to put the ugly?

Shall we move this conversation to #818 as the concrete impl is on display there?
