### ISSUE TITLE
[Feature]: Oracle DB support

### ISSUE THREAD

**Issue by Dzeri96** [projectnessie/nessie#8680]
### Description

I recently came across this project and have noticed that Oracle DB is currently not supported. My question is, how much work would it be to include support for the Oracle JDBC driver, or could we even possibly piggyback off of the existing PostgreSQL support?

I'm guessing that the demand is not really there, but for my team it might even be easier to contribute this driver rather than build a data versioning tool from scratch.

### Expected Use Cases

Nessie can be used on Oracle DB.

### Requested Changes in public API

None

**Comment by dimas-b** [comment]
Coding work is probably not huge. Quarkus appears to support it. Cf. #8483, #8548, #8545.

The biggest question is the driver's license terms. It might be more convenience to discuss that in Zulip. Would you like to open a topic on that there? (the join link is on projectnessie.org).

**Comment by Dzeri96** [comment]
Sure, I'll take the discussion there during the coming week. You can close this issue if you want.

**Comment by adutra** [comment]
@Dzeri96 unfortunately, it's not going to be possible to include support for Oracle, due to licensing issues. If you are interested, I can give you guidelines as to how to build Nessie yourself, with support for Oracle. Just let me know.

**Comment by Dzeri96** [comment]
That's too bad, but I can't say I'm surprised. Just out of curiosity though, what makes nessie different from say, liquibase, that even ships with an oracle driver? Do they pay a fee for this?

In terms of building the project, I'll reach out if we decide to go that route. For now you can close this issue.

**Comment by snazy** [comment]
The problem AFAIU (I'm not a lawyer) is, that you may easily get into a "pay us" trap, when you (re)distribute w/ "amounts" attached - either internally in a company or externally. We prefer to stay away from these licenses - pretty much like the ASF [does here](https://www.apache.org/legal/resolved.html#category-x).

The technical issue wrt licensing is that we would have to include the driver in all the Nessie server distributions, due to how Quarkus builds work.
